spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false


server:
  port: 10320


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always