spring:
  application:
    name: gateway-server
  profiles:
    active: dev
server:
  port: 10320

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always