### 로그인 요청
POST http://localhost:10320/auth/login
Content-Type: application/json

{
  "userId": "adminuser",
  "password": "1234"
}

### 토큰 재발급 요청
POST http://localhost:10320/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbnVzZXIiLCJpYXQiOjE3NDk3ODMwMDksImV4cCI6MTc0OTg2OTQwOX0.WPmeUBry6dIKjL-YRt5EjLXhXpdPRzzUTjVI_MRetNs"
}

### 토큰 인증 요청 테스트
GET http://localhost:10320/admin/secure-endpoint
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbnVzZXIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc0OTc4MzEyNSwiZXhwIjoxNzQ5Nzg2NzI1fQ.EpK2ujRd8CCoDMKbA8h8maYhpZw5-QHOz45W-ByAmVs
